# Generated by Django 4.2.2 on 2023-06-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_available_payments_alter_users_bought_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='available_payments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
