# Generated by Django 4.2.3 on 2023-07-23 10:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_paymentsaccounts_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='available_payments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
    ]
