# Generated by Django 4.2.3 on 2023-07-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_users_available_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='available_payments',
        ),
        migrations.DeleteModel(
            name='PaymentsAccounts',
        ),
    ]
