# Generated by Django 4.2.3 on 2023-07-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_users_available_payments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_address',
        ),
    ]
