# Generated by Django 4.2.3 on 2023-07-24 16:10

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_users_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_image',
            field=models.CharField(default=users.models.get_default_profile_image, max_length=500),
        ),
    ]
