# Generated by Django 4.2.3 on 2023-07-27 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_users_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='verification_token',
        ),
    ]
