# Generated by Django 4.2.3 on 2023-07-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_item_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_link',
            field=models.CharField(default='no link', max_length=300),
        ),
    ]
