# Generated by Django 4.2.3 on 2023-07-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_item_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
