# Generated by Django 4.2.3 on 2023-07-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_delete_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_link',
            field=models.CharField(max_length=500),
        ),
    ]
