# Generated by Django 4.2.3 on 2023-07-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_item_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image1',
            field=models.CharField(default='https://raw.githubusercontent.com/lou320/weee_images/main/noimage.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image2',
            field=models.CharField(default='https://raw.githubusercontent.com/lou320/weee_images/main/noimage.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image3',
            field=models.CharField(default='https://raw.githubusercontent.com/lou320/weee_images/main/noimage.jpg', max_length=500),
        ),
    ]
