# Generated by Django 4.2.3 on 2023-07-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_item_item_image1_alter_item_item_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image1',
            field=models.CharField(default='https://github.com/lou320/weee_images/blob/main/noimage.jpg?raw=true', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image2',
            field=models.CharField(default='https://github.com/lou320/weee_images/blob/main/noimage.jpg?raw=true', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image3',
            field=models.CharField(default='https://github.com/lou320/weee_images/blob/main/noimage.jpg?raw=true', max_length=500),
        ),
    ]
