# Generated by Django 4.2.3 on 2023-07-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_item_item_image1_alter_item_item_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
