# Generated by Django 4.2.3 on 2023-10-26 04:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_delete_imagestore_item_image123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image123',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image1',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image2',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image3',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
